// <auto-generated />
using System;
using System.Text.Json;
using Consular.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Consular.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260729141818_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Consular.Shared.Entities.Citoyen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Region")
                        .HasColumnType("integer");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Citoyens");
                });

            modelBuilder.Entity("Consular.Shared.Entities.Demande", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("Attributs")
                        .HasColumnType("jsonb");

                    b.Property<string>("CanalDepot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("CitoyenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateDepot")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EquipeAssignee")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NoteDocumentsManquantes")
                        .HasColumnType("text");

                    b.Property<string>("NumeroReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Region")
                        .HasColumnType("integer");

                    b.Property<Guid>("StatutId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TypeServiceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CitoyenId");

                    b.HasIndex("NumeroReference")
                        .IsUnique();

                    b.HasIndex("StatutId");

                    b.HasIndex("TypeServiceId");

                    b.ToTable("Demandes");
                });

            modelBuilder.Entity("Consular.Shared.Entities.DemandeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CheminStockage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DemandeId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ValideParAgent")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DemandeId");

                    b.ToTable("DemandeDocuments");
                });

            modelBuilder.Entity("Consular.Shared.Entities.DemandeEtatCivil", b =>
                {
                    b.Property<Guid>("DemandeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateEvenement")
                        .HasColumnType("date");

                    b.Property<string>("LieuEvenement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeActe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DemandeId");

                    b.ToTable("DemandeEtatCivils");
                });

            modelBuilder.Entity("Consular.Shared.Entities.DemandeHistorique", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorName")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateChangement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DemandeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<Guid>("StatutDestinationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StatutOrigineId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StatutDestinationId");

                    b.HasIndex("StatutOrigineId");

                    b.HasIndex("DemandeId", "DateChangement");

                    b.ToTable("DemandeHistoriques");
                });

            modelBuilder.Entity("Consular.Shared.Entities.DemandeVisa", b =>
                {
                    b.Property<Guid>("DemandeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateEntreePrevue")
                        .HasColumnType("date");

                    b.Property<int>("DureeSejourJours")
                        .HasColumnType("integer");

                    b.Property<string>("PaysDestination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeVisa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DemandeId");

                    b.ToTable("DemandeVisas");
                });

            modelBuilder.Entity("Consular.Shared.Entities.NotificationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Canal")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DemandeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Destinataire")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferenceFournisseur")
                        .HasColumnType("text");

                    b.Property<int>("StatutEnvoi")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DemandeId");

                    b.ToTable("NotificationLogs");
                });

            modelBuilder.Entity("Consular.Shared.Entities.Statut", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("EstFinal")
                        .HasColumnType("boolean");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Statuts");
                });

            modelBuilder.Entity("Consular.Shared.Entities.TypeService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<int>("Categorie")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TypeServices");
                });

            modelBuilder.Entity("Consular.Shared.Entities.Demande", b =>
                {
                    b.HasOne("Consular.Shared.Entities.Citoyen", "Citoyen")
                        .WithMany("Demandes")
                        .HasForeignKey("CitoyenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Consular.Shared.Entities.Statut", "Statut")
                        .WithMany()
                        .HasForeignKey("StatutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Consular.Shared.Entities.TypeService", "TypeService")
                        .WithMany("Demandes")
                        .HasForeignKey("TypeServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Citoyen");

                    b.Navigation("Statut");

                    b.Navigation("TypeService");
                });

            modelBuilder.Entity("Consular.Shared.Entities.DemandeDocument", b =>
                {
                    b.HasOne("Consular.Shared.Entities.Demande", null)
                        .WithMany("Documents")
                        .HasForeignKey("DemandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Consular.Shared.Entities.DemandeEtatCivil", b =>
                {
                    b.HasOne("Consular.Shared.Entities.Demande", "Demande")
                        .WithOne("DemandeEtatCivil")
                        .HasForeignKey("Consular.Shared.Entities.DemandeEtatCivil", "DemandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demande");
                });

            modelBuilder.Entity("Consular.Shared.Entities.DemandeHistorique", b =>
                {
                    b.HasOne("Consular.Shared.Entities.Demande", null)
                        .WithMany("Historique")
                        .HasForeignKey("DemandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Consular.Shared.Entities.Statut", "StatutDestination")
                        .WithMany()
                        .HasForeignKey("StatutDestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Consular.Shared.Entities.Statut", "StatutOrigine")
                        .WithMany()
                        .HasForeignKey("StatutOrigineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("StatutDestination");

                    b.Navigation("StatutOrigine");
                });

            modelBuilder.Entity("Consular.Shared.Entities.DemandeVisa", b =>
                {
                    b.HasOne("Consular.Shared.Entities.Demande", "Demande")
                        .WithOne("DemandeVisa")
                        .HasForeignKey("Consular.Shared.Entities.DemandeVisa", "DemandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demande");
                });

            modelBuilder.Entity("Consular.Shared.Entities.NotificationLog", b =>
                {
                    b.HasOne("Consular.Shared.Entities.Demande", null)
                        .WithMany("Notifications")
                        .HasForeignKey("DemandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Consular.Shared.Entities.Citoyen", b =>
                {
                    b.Navigation("Demandes");
                });

            modelBuilder.Entity("Consular.Shared.Entities.Demande", b =>
                {
                    b.Navigation("DemandeEtatCivil");

                    b.Navigation("DemandeVisa");

                    b.Navigation("Documents");

                    b.Navigation("Historique");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Consular.Shared.Entities.TypeService", b =>
                {
                    b.Navigation("Demandes");
                });
#pragma warning restore 612, 618
        }
    }
}
