// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using Consular.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Consular.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Consular.Shared.Entities.AdminAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AdminAuditLogs");
                });

            modelBuilder.Entity("Consular.Shared.Entities.Applicant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MotDePasseHash")
                        .HasColumnType("text");

                    b.Property<string>("Nationalite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Applicants");
                });

            modelBuilder.Entity("Consular.Shared.Entities.AppointmentSlotTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<int>("CapaciteMax")
                        .HasColumnType("integer");

                    b.Property<int>("Categorie")
                        .HasColumnType("integer");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int>("Region")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Region", "Categorie", "DayOfWeek", "StartTime")
                        .IsUnique();

                    b.ToTable("AppointmentSlotTemplates");
                });

            modelBuilder.Entity("Consular.Shared.Entities.Demande", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("Attributs")
                        .HasColumnType("jsonb");

                    b.Property<string>("CanalDepot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("DateDepot")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EquipeAssignee")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NoteDocumentsManquantes")
                        .HasColumnType("text");

                    b.Property<string>("NoteRejet")
                        .HasColumnType("text");

                    b.Property<string>("NumeroReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RendezVousBiometrieAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SoumisParApplicantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SoumisParUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StatutId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TypeServiceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("NumeroReference")
                        .IsUnique();

                    b.HasIndex("SoumisParApplicantId");

                    b.HasIndex("SoumisParUserId");

                    b.HasIndex("StatutId");

                    b.HasIndex("TypeServiceId");

                    b.ToTable("Demandes");
                });

            modelBuilder.Entity("Consular.Shared.Entities.DemandeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CheminStockage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DemandeId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ValideParAgent")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DemandeId");

                    b.ToTable("DemandeDocuments");
                });

            modelBuilder.Entity("Consular.Shared.Entities.DemandeEtatCivil", b =>
                {
                    b.Property<Guid>("DemandeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateEvenement")
                        .HasColumnType("date");

                    b.Property<string>("LieuEvenement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeActe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DemandeId");

                    b.ToTable("DemandeEtatCivils");
                });

            modelBuilder.Entity("Consular.Shared.Entities.DemandeHistorique", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorName")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateChangement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DemandeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<Guid>("StatutDestinationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StatutOrigineId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StatutDestinationId");

                    b.HasIndex("StatutOrigineId");

                    b.HasIndex("DemandeId", "DateChangement");

                    b.ToTable("DemandeHistoriques");
                });

            modelBuilder.Entity("Consular.Shared.Entities.DemandePasseport", b =>
                {
                    b.Property<Guid>("DemandeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DateExpirationActuelle")
                        .HasColumnType("date");

                    b.Property<string>("NumeroPasseportActuel")
                        .HasColumnType("text");

                    b.Property<string>("TypeDemande")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DemandeId");

                    b.ToTable("DemandePasseports");
                });

            modelBuilder.Entity("Consular.Shared.Entities.DemandeVisa", b =>
                {
                    b.Property<Guid>("DemandeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateEntreePrevue")
                        .HasColumnType("date");

                    b.Property<int>("DureeSejourJours")
                        .HasColumnType("integer");

                    b.Property<string>("PaysDestination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeVisa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DemandeId");

                    b.ToTable("DemandeVisas");
                });

            modelBuilder.Entity("Consular.Shared.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Consular.Shared.Entities.RegionLookup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LibelleEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LibelleFr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.Property<int>("Valeur")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("RegionLookups");
                });

            modelBuilder.Entity("Consular.Shared.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Consular.Shared.Entities.Statut", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("EstFinal")
                        .HasColumnType("boolean");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Statuts");
                });

            modelBuilder.Entity("Consular.Shared.Entities.TypeService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<int>("Categorie")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<List<string>>("DocumentsRequisEn")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<List<string>>("DocumentsRequisFr")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("MontantFrais")
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TypeServices");
                });

            modelBuilder.Entity("Consular.Shared.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Region")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<Guid>("PermissionsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("PermissionsId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("PermissionRole");
                });

            modelBuilder.Entity("Consular.Shared.Entities.Demande", b =>
                {
                    b.HasOne("Consular.Shared.Entities.Applicant", "Applicant")
                        .WithMany("Demandes")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Consular.Shared.Entities.Applicant", "SoumisParApplicant")
                        .WithMany()
                        .HasForeignKey("SoumisParApplicantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Consular.Shared.Entities.User", "SoumisParUser")
                        .WithMany()
                        .HasForeignKey("SoumisParUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Consular.Shared.Entities.Statut", "Statut")
                        .WithMany()
                        .HasForeignKey("StatutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Consular.Shared.Entities.TypeService", "TypeService")
                        .WithMany("Demandes")
                        .HasForeignKey("TypeServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("SoumisParApplicant");

                    b.Navigation("SoumisParUser");

                    b.Navigation("Statut");

                    b.Navigation("TypeService");
                });

            modelBuilder.Entity("Consular.Shared.Entities.DemandeDocument", b =>
                {
                    b.HasOne("Consular.Shared.Entities.Demande", null)
                        .WithMany("Documents")
                        .HasForeignKey("DemandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Consular.Shared.Entities.DemandeEtatCivil", b =>
                {
                    b.HasOne("Consular.Shared.Entities.Demande", "Demande")
                        .WithOne("DemandeEtatCivil")
                        .HasForeignKey("Consular.Shared.Entities.DemandeEtatCivil", "DemandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demande");
                });

            modelBuilder.Entity("Consular.Shared.Entities.DemandeHistorique", b =>
                {
                    b.HasOne("Consular.Shared.Entities.Demande", null)
                        .WithMany("Historique")
                        .HasForeignKey("DemandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Consular.Shared.Entities.Statut", "StatutDestination")
                        .WithMany()
                        .HasForeignKey("StatutDestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Consular.Shared.Entities.Statut", "StatutOrigine")
                        .WithMany()
                        .HasForeignKey("StatutOrigineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("StatutDestination");

                    b.Navigation("StatutOrigine");
                });

            modelBuilder.Entity("Consular.Shared.Entities.DemandePasseport", b =>
                {
                    b.HasOne("Consular.Shared.Entities.Demande", "Demande")
                        .WithOne("DemandePasseport")
                        .HasForeignKey("Consular.Shared.Entities.DemandePasseport", "DemandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demande");
                });

            modelBuilder.Entity("Consular.Shared.Entities.DemandeVisa", b =>
                {
                    b.HasOne("Consular.Shared.Entities.Demande", "Demande")
                        .WithOne("DemandeVisa")
                        .HasForeignKey("Consular.Shared.Entities.DemandeVisa", "DemandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demande");
                });

            modelBuilder.Entity("Consular.Shared.Entities.User", b =>
                {
                    b.HasOne("Consular.Shared.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.HasOne("Consular.Shared.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Consular.Shared.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Consular.Shared.Entities.Applicant", b =>
                {
                    b.Navigation("Demandes");
                });

            modelBuilder.Entity("Consular.Shared.Entities.Demande", b =>
                {
                    b.Navigation("DemandeEtatCivil");

                    b.Navigation("DemandePasseport");

                    b.Navigation("DemandeVisa");

                    b.Navigation("Documents");

                    b.Navigation("Historique");
                });

            modelBuilder.Entity("Consular.Shared.Entities.TypeService", b =>
                {
                    b.Navigation("Demandes");
                });
#pragma warning restore 612, 618
        }
    }
}
